---
- name: Destroy VPC and EC2
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_id }}"
        region: "{{ region }}"
        state: absent
      register: ec2_termination

    - name: Delete security group
      amazon.aws.ec2_group:
        group_id: "{{ sg_id }}"
        region: "{{ region }}"
        state: absent
      register: sg_deletion

    - name: Delete SG ID to vars.yml
      ansible.builtin.lineinfile:
        path: ./vars.yml
        regexp: 'sg_id: {{sg_id}}'
        state: absent
    
    - name: Delete EC2 ID to vars.yml
      ansible.builtin.lineinfile:
        path: ./vars.yml
        regexp: 'ec2_id: {{ec2_id}}'
        state: absent

    - name: Delete EC2 IP to vars.yml
      ansible.builtin.lineinfile:
        path: ./vars.yml
        regexp: 'ec2_ip: {{ec2_ip}}'
        state: absent
    
    - name: Delete Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        tags:
          Name: "{{ vpc_name }}_RT"
        region: "{{region}}"
        subnets:
          - "{{subnet_id}}"
        state: absent
      register: rt

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ vpc_name }}_IGW"
        state: absent
      register: igw

    - name: Delete Subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ subnet_cidr_block }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        state: absent
        wait: yes
      register: subnet
      with_items:
          - {subnet_name: "{{vpc_name}}_public"}

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ region }}"
        dns_hostnames: yes
        dns_support: yes
        tags:
          Name: "{{ vpc_name }}"
        state: absent
      register: vpc

    - name: Remove VPC ID from vars.yml
      ansible.builtin.lineinfile:
        path: ./vars.yml
        regexp: 'vpc_id: {{ vpc_id }}'
        state: absent
    
    - name: Remove Subnet ID from vars.yml
      ansible.builtin.lineinfile:
        path: ./vars.yml
        regexp: 'subnet_id: {{ subnet_id }}'
        state: absent

     
